### ISSUE TITLE
Use TypeScript

### ISSUE THREAD

**Issue by prendradjaja** [marwahaha/friendlog#39]
because omg js

**Comment by marwahaha** [comment]
I don't see a need here unless we'd like to learn typescript - it seems robust enough.

There are a few projects to lint and gen TS files (https://github.com/Microsoft/dtslint and https://github.com/Microsoft/dts-gen ) and I think a typings file wouldn't be a bad idea.

What about flow? If you'd like to learn it, we could try it out

**Comment by prendradjaja** [comment]
Yeah, no particular need. But I definitely do want to understand TS a bit
better so it could be good for learning! Flow could be cool to learn about
too.

**Comment by marwahaha** [comment]
This seems out of scope for the project. Thanks!
